import React, { useRef, useState } from "react";
import { Entypo } from "@expo/vector-icons";
import {
  getDownloadURL,
  getStorage,
  ref as storageRef,
  uploadBytes,
} from "@firebase/storage";
import {
  TextInput,
  TouchableOpacity,
  Text,
  StyleSheet,
  Alert,
  View,
  Image,
  Platform,
} from "react-native";
import {
  doc,
  setDoc,
  getFirestore,
  addDoc,
  collection,
} from "firebase/firestore";
import { useDispatch, useSelector } from "react-redux";
import { RootState } from "../redux/store";
import { setProfile } from "../redux/slices/profilleSlice";
import ScreenWrapper from "../components/ScreenWrapper";
import { height, width } from "../utills/Dimension";
import { Color } from "../utills/GlobalStyles";
import Button from "../components/button";
import { setAppLoader } from "../redux/slices/loaderSlice";
import { successMessage } from "../utills/GlobalMethods";
import FilePickerModal from "../components/filepiker";
import { setUser } from "../redux/slices/userSlice";
const EditProfileScreen = ({ navigation }: { navigation: any }) => {
  const user = useSelector((state: RootState) => state.user);
  const profile = useSelector((state: RootState) => state.profile);
  const imageRef = useRef(null);
  const [image, setImage] = React.useState([profile?.photoURL]);

  const [username, setUsername] = useState(profile.username);
  const [phoneNumber, setPhoneNumber] = useState(profile.phoneNumber + "");
  const [email, setEmail] = useState(profile.email);
  const [businessName, setBusinessName] = useState(profile.photoURL);
  const [address, setAddress] = useState(profile.address);

  const db = getFirestore();
  const dispatch = useDispatch();
  async function getBlobFromFile(imageUri: any) {
    return (await fetch(imageUri)).blob();
  }
  const saveImages = async () => {
    if (!username || !phoneNumber || !email || !businessName || !address) {
      Alert.alert("Error", "All fields are required except the image.");
      return;
    }

    if (image.length === 0) {
      dispatch(setAppLoader(true));
      saveProfile(profile.photoURL);
      return;
    }
    if (image[0] === profile.photoURL) {
      dispatch(setAppLoader(true));
      saveProfile(profile.photoURL);
      return;
    }
    try {
      dispatch(setAppLoader(true));
      const imageUrls = [];
      const storage = getStorage();

      for (const imageUri of image) {
        const split = imageUri.split("/");
        const name = split.pop();
        const imageRef = storageRef(
          storage,
          `Users/${profile.userId}/images/${name}`
        );

        const metadata = {
          contentType: "image/jpeg",
        };

        // // Get the blob from the image URI
        try {
          const imageBlob = await getBlobFromFile(imageUri);

          const uploadTask = await uploadBytes(
            imageRef,
            imageBlob,
            metadata
          ).catch((err) => {
            console.log("Error uploading images:", err);
          });
          const snapshot = await uploadTask;

          if (snapshot) {
            const downloadUrl = await getDownloadURL(imageRef);
            if (downloadUrl) {
              imageUrls.push(downloadUrl);
            }
          }
        } catch (error) {
          console.log("Error uploading images:", error);
          dispatch(setAppLoader(false));
        }
      }

      if (imageUrls.length > 0) {
        console.log("set to sever now in profile", imageUrls[0]);

        saveProfile(imageUrls[0]);
      }

      // dispatch(setAppLoader(false));
      setImage([]);
    } catch (error) {
      console.log("muktipule iamge", error);
      dispatch(setAppLoader(false));
    }
  };
  const saveProfile = async (photoURL = "") => {
    try {
      const isProfille =
        !!profile.username && !!profile.phoneNumber && !!profile.email;
      let autoGeneratedId;

      console.log("isProfille", isProfille);
      if (!isProfille) {
        const docRef = await addDoc(collection(db, "branches"), {
          branchName: businessName,
          userId: user.uid,
        });

        // Get the auto-generated ID
        autoGeneratedId = docRef.id;
      }
      console.log("Document written with ID: ", autoGeneratedId);

      const branchIds = !!autoGeneratedId
        ? [autoGeneratedId]
        : profile.branchIds;

      const selectedBranchId = !!autoGeneratedId
        ? autoGeneratedId
        : profile.selectedBranchId;

      await setDoc(doc(db, "users", user.uid), {
        username,
        phoneNumber,
        email,
        address,
        photoURL,
        branchIds,
      });
      dispatch(
        setProfile({
          username,
          phoneNumber,
          email,
          address,
          userId: user.uid,
          branchIds,
          branchName: businessName,
        }),
      );

      // Alert.alert("Success", "Profile saved successfully!", [
      //   { text: "OK", onPress: () =>  },
      // ]);
      dispatch(setAppLoader(false));
      successMessage("Profile Updated");
      // navigation.goBack();
    } catch (error) {
      console.log(error);
      Alert.alert("Error", "Failed to save profile.");
    } finally {
      // setLoading(false);
      dispatch(setAppLoader(false));
    }
  };
  console.log(image);

  return (
    <ScreenWrapper scrollEnabled>
      <View style={styles.container}>
        <Text style={styles.title}>Profile</Text>
        <TouchableOpacity
          style={{
            alignSelf: "center",
            borderRadius: height(10),
          }}
          onPress={() => imageRef.current.show()}
        >
          <Image
            source={{
              uri:
                image[0] ||
                "https://cdn-icons-png.flaticon.com/512/149/149071.png",
            }}
            style={styles.image}
          />
          <View style={styles.camera}>
            <Entypo name="camera" size={height(3)} color={Color.primaryColor} />
          </View>
        </TouchableOpacity>

        <Text style={styles.text}>Name</Text>
        <TextInput
          style={styles.input}
          placeholder="Username"
          value={username}
          onChangeText={setUsername}
        />
        <Text style={styles.text}>Phone Number</Text>

        <TextInput
          style={styles.input}
          placeholder="Phone Number"
          value={phoneNumber}
          onChangeText={setPhoneNumber}
          editable={false}
        />
        <Text style={styles.text}>Email</Text>

        <TextInput
          style={styles.input}
          placeholder="Email"
          value={email}
          onChangeText={setEmail}
        />
        <Text style={styles.text}>Address</Text>

        <TextInput
          style={styles.input}
          placeholder="Business Name"
          value={businessName}
          onChangeText={setBusinessName}
        />
        <Text style={styles.text}>Business Name</Text>

        <TextInput
          style={styles.input}
          placeholder="Address"
          value={address}
          onChangeText={setAddress}
        />
        <Button
          title={"Save Profile"}
          onPress={saveImages}
          containerStyle={{ width: width(90), marginTop: height(3) }}
        />
      </View>
      <FilePickerModal
        ref={imageRef}
        onFilesSelected={(img) => {
          const selectedImages = img.map((imageUri) => {
            return Platform.OS === "android"
              ? imageUri.uri
              : imageUri.uri.replace("file://", "");
            //}
          });
          setImage(selectedImages);
        }}
      />
    </ScreenWrapper>
  );
};

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    padding: height(2),
  },
  title: {
    fontSize: height(3),
    fontWeight: "bold",
    textAlign: "center",
    marginVertical: height(3),
    color: Color.primaryColor,
  },
  text: {
    textAlign: "left",
    width: "100%",
    fontSize: height(1.8),
    fontWeight: "700",
  },
  input: {
    borderColor: "#ced4da",
    padding: 12,
    marginVertical: width(2),
    borderRadius: height(3),
    backgroundColor: Color.backgroundColor,
  },
  saveButton: {
    backgroundColor: "#007bff",
    padding: 15,
    borderRadius: 8,
    marginVertical: 10,
  },
  saveButtonText: {
    color: "#fff",
    textAlign: "center",
    fontWeight: "bold",
  },
  loadingContainer: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    zIndex: 1,
  },
  image: {
    width: height(20),
    height: height(20),
    alignSelf: "center",
    marginVertical: height(1),
    borderWidth: height(0.3),
    borderColor: Color.secondaryColor,
    borderRadius: height(20),
  },
  camera: {
    position: "absolute",
    bottom: height(2),
    right: height(2),
    backgroundColor: Color.secondaryColor,
    padding: height(0.5),
    borderRadius: height(5),
  },
});

export default EditProfileScreen;
